server:
  port: 8081
spring:
  profiles:
    active: dev #生产环境
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///leyou?characterEncoding=UTF-8
    username: root
    password: root
#myBatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #输出sql日志
  mapper-locations: classpath*:mapper/**Mapper.xml
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: ${spring.application.name}